// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6KZW922Gkdios-p6M-tX3ajxLUhhi_dM',
    appId: '1:178320484508:web:da995c7b4ab493ffe0e559',
    messagingSenderId: '178320484508',
    projectId: 'smart-multi-meter',
    authDomain: 'smart-multi-meter.firebaseapp.com',
    databaseURL: 'https://smart-multi-meter-default-rtdb.firebaseio.com',
    storageBucket: 'smart-multi-meter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6KZW922Gkdios-p6M-tX3ajxLUhhi_dM',
    appId: '1:178320484508:android:da995c7b4ab493ffe0e559',
    messagingSenderId: '178320484508',
    projectId: 'smart-multi-meter',
    databaseURL: 'https://smart-multi-meter-default-rtdb.firebaseio.com',
    storageBucket: 'smart-multi-meter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6KZW922Gkdios-p6M-tX3ajxLUhhi_dM',
    appId: '1:178320484508:ios:da995c7b4ab493ffe0e559',
    messagingSenderId: '178320484508',
    projectId: 'smart-multi-meter',
    databaseURL: 'https://smart-multi-meter-default-rtdb.firebaseio.com',
    storageBucket: 'smart-multi-meter.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6KZW922Gkdios-p6M-tX3ajxLUhhi_dM',
    appId: '1:178320484508:ios:da995c7b4ab493ffe0e559',
    messagingSenderId: '178320484508',
    projectId: 'smart-multi-meter',
    databaseURL: 'https://smart-multi-meter-default-rtdb.firebaseio.com',
    storageBucket: 'smart-multi-meter.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );
}
